import api from './api';

const adminService = {
  getStats: () => api.get('/admin/stats'),
  getUsers: (params) => api.get('/admin/users', { params }),
  updateUser: (id, data) => api.put(`/admin/users/${id}`, data),
  getProviders: (params) => api.get('/admin/providers', { params }),
  getProviderDetails: (id) => api.get(`/admin/providers/${id}/details`),
  verifyProvider: (id, data) => api.put(`/admin/providers/${id}/verify`, data),
  getDashboardSummary: () => api.get('/admin/dashboard/summary'),
  getDashboardRevenue: (period) => api.get('/admin/dashboard/revenue', { params: { period } }),
  getTopProviders: (limit = 10) => api.get('/admin/dashboard/top-providers', { params: { limit } }),
  getDashboardBookings: () => api.get('/admin/dashboard/bookings'),
  getFraudSummary: () => api.get('/admin/fraud/summary'),
  getFraudFlags: (params) => api.get('/admin/fraud/flags', { params }),
  takeFraudAction: (data) => api.post('/admin/fraud/action', data),
  getPincodes: () => api.get('/admin/pincodes/list'),
  addPincode: (data) => api.post('/admin/pincodes/add', data),
  togglePincode: (id) => api.put(`/admin/pincodes/${id}/toggle`),
  createPlan: (data) => api.post('/admin/plans/create', data),
  getPlans: () => api.get('/admin/plans'),
  updatePlan: (id, data) => api.put(`/admin/plans/${id}`, data),
  createPackage: (data) => api.post('/admin/packages/create', data),
  getPackages: () => api.get('/admin/packages'),
  updatePackage: (id, data) => api.put(`/admin/packages/${id}`, data),
  getPendingAssignments: () => api.get('/admin/assignments/pending'),
  assignProvider: (data) => api.post('/admin/assign-provider', data),
  getServicePricing: () => api.get('/admin/services/pricing'),
  updateServicePricing: (id, data) => api.put(`/admin/services/${id}/pricing`, data),
  setAdminPrice: (bookingId, data) => api.put(`/admin/bookings/${bookingId}/set-price`, data),
  getProviderLeads: (params) => api.get('/admin/leads', { params }),
  updateLeadStatus: (id, data) => api.put(`/admin/leads/${id}`, data),
  updateProviderOnboarding: (id, data) => api.put(`/admin/providers/${id}/onboarding-status`, data),
  getSupplyGaps: () => api.get('/admin/supply-gaps'),
  createPage: (data) => api.post('/admin/content/pages', data),
  listPages: (params) => api.get('/admin/content/pages', { params }),
  getPage: (id) => api.get(`/admin/content/pages/${id}`),
  updatePage: (id, data) => api.put(`/admin/content/pages/${id}`, data),
  deletePage: (id) => api.delete(`/admin/content/pages/${id}`),
  uploadPageHero: (id, formData) => api.post(`/admin/content/pages/${id}/hero`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  createBlog: (data) => api.post('/admin/blogs', data),
  listBlogs: (params) => api.get('/admin/blogs', { params }),
  getBlog: (id) => api.get(`/admin/blogs/${id}`),
  updateBlog: (id, data) => api.put(`/admin/blogs/${id}`, data),
  deleteBlog: (id) => api.delete(`/admin/blogs/${id}`),
  uploadBlogHero: (id, formData) => api.post(`/admin/blogs/${id}/hero`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
};

export default adminService;
