import api from './api';

const labService = {
  // Public / Patient
  getLabs: () => api.get('/labs'),
  getDepartments: () => api.get('/labs/departments'),
  searchTests: (params) => api.get('/labs/tests', { params }),
  getLabById: (id) => api.get(`/labs/${id}`),
  bookTest: (data) => api.post('/lab/orders', data),
  getMyOrders: () => api.get('/labs/me/orders'),
  getInvoice: (id) => api.get(`/invoices/${id}`),
  getReport: (id) => api.get(`/reports/${id}`),
  getFamilyMembers: () => api.get('/members'),
  addFamilyMember: (data) => api.post('/members', data),
  updateFamilyMember: (id, data) => api.put(`/members/${id}`, data),
  deleteFamilyMember: (id) => api.delete(`/members/${id}`),
  getSavedAddresses: () => api.get('/addresses'),
  addSavedAddress: (data) => api.post('/addresses', data),
  updateSavedAddress: (id, data) => api.put(`/addresses/${id}`, data),
  deleteSavedAddress: (id) => api.delete(`/addresses/${id}`),

  // Partner
  registerPartner: (data) => api.post('/partner/lab/register', data),
  loginPartner: (data) => api.post('/partner/lab/login', data),
  getPartnerProfile: () => api.get('/partner/lab/profile'),
  updatePartnerProfile: (data) => api.put('/partner/lab/profile', data),
  getPartnerDashboard: () => api.get('/partner/lab/dashboard'),
  getPartnerFinancialSummary: () => api.get('/partner/lab/financial-summary'),
  getPartnerOrders: (filter) => api.get('/partner/lab/orders', { params: filter && filter !== 'all' ? { status: filter } : {} }),
  updatePartnerOrderStatus: (id, data) => api.put(`/partner/lab/orders/${id}/status`, data),
  getPartnerTests: (params) => api.get('/partner/lab/tests', { params }),
  addPartnerTest: (data) => api.post('/partner/lab/tests', data),
  updatePartnerTest: (id, data) => api.put(`/partner/lab/tests/${id}`, data),
  deletePartnerTest: (id) => api.delete(`/partner/lab/tests/${id}`),
  bulkUploadPartnerTests: (data) => api.post('/partner/lab/tests/bulk', data),
  getPartnerStaff: () => api.get('/partner/lab/staff'),
  addPartnerStaff: (data) => api.post('/partner/lab/staff', data),
  updatePartnerStaff: (id, data) => api.put(`/partner/lab/staff/${id}`, data),
  updatePartnerStaffStatus: (id, data) => api.put(`/partner/lab/staff/${id}/status`, data),
  deletePartnerStaff: (id) => api.delete(`/partner/lab/staff/${id}`),
  togglePartnerStaff: (id) => api.patch(`/partner/lab/staff/${id}/status`),
  uploadPartnerReport: (id, formData) => api.post(`/partner/lab/orders/${id}/report`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  getPartnerWallet: () => api.get('/partner/lab/wallet'),
  getPartnerTransactions: (params) => api.get('/partner/lab/wallet/transactions', { params }),
  requestPartnerPayout: (amount) => api.post('/partner/lab/wallet/payout', { amount }),

  // Admin
  getAdminPartners: () => api.get('/admin/labs/partners'),
  updateAdminPartnerStatus: (id, data) => api.put(`/admin/labs/partners/${id}/status`, data),
  getAdminTests: () => api.get('/admin/labs/tests'),
  updateAdminTestPricing: (id, data) => api.put(`/admin/labs/tests/${id}/pricing`, data),
  updateAdminDepartmentCommissions: (partnerId, data) => api.put(`/admin/labs/partners/${partnerId}/department-commissions`, data),
  updateLabCommission: (labId, data) => api.put(`/admin/labs/${labId}/commission`, data),
  getAdminAllOrders: () => api.get('/admin/labs/orders'),
  getAdminAnalytics: () => api.get('/admin/labs/analytics'),
  getAdminFinanceMetrics: () => api.get('/admin/labs/finance/metrics'),
  processAdminSettlement: (data) => api.post('/admin/labs/finance/settlements', data),
  manageAdminFinanceStatus: (id, data) => api.put(`/admin/labs/orders/${id}/finance-status`, data),
  getAdminReconciliation: (params) => api.get('/admin/labs/reconciliation', { params }),
  getAdminReconciliationOrders: (params) => api.get('/admin/labs/reconciliation/orders', { params }),
  settleAdminReconciliation: (data) => api.post('/admin/labs/reconciliation/settle', data),
  flagAdminReconciliation: (data) => api.put('/admin/labs/reconciliation/flag', data),

  // Aliases for backward compatibility with merged usage
  getPartners: () => api.get('/admin/labs/partners'),
  getAllOrders: () => api.get('/admin/labs/orders'),
  getAnalytics: () => api.get('/admin/labs/analytics'),
  getFinanceMetrics: () => api.get('/admin/labs/finance/metrics'),
  getReconciliation: (params) => api.get('/admin/labs/reconciliation', { params }),
  getReconciliationOrders: (params) => api.get('/admin/labs/reconciliation/orders', { params }),
  settleReconciliation: (data) => api.post('/admin/labs/reconciliation/settle', data),
  flagReconciliation: (data) => api.put('/admin/labs/reconciliation/flag', data),
  getOrders: (filter) => api.get('/partner/lab/orders', { params: filter && filter !== 'all' ? { status: filter } : {} }),
  getProfile: () => api.get('/partner/lab/profile'),
  updateProfile: (data) => api.put('/partner/lab/profile', data),
  getDashboard: () => api.get('/partner/lab/dashboard'),
  getStaff: () => api.get('/partner/lab/staff'),
  getTests: (params) => api.get('/partner/lab/tests', { params }),
  getFinancialSummary: () => api.get('/partner/lab/financial-summary'),
  addStaff: (data) => api.post('/partner/lab/staff', data),
  updateStaffStatus: (id, data) => api.put(`/partner/lab/staff/${id}/status`, data),
  addTest: (data) => api.post('/partner/lab/tests', data),
  bulkUploadTests: (data) => api.post('/partner/lab/tests/bulk', data),
  updateStaff: (id, data) => api.put(`/partner/lab/staff/${id}`, data),
  deleteStaff: (id) => api.delete(`/partner/lab/staff/${id}`),
  updateTest: (id, data) => api.put(`/partner/lab/tests/${id}`, data),
  deleteTest: (id) => api.delete(`/partner/lab/tests/${id}`),
  updateOrderStatus: (id, data) => api.put(`/partner/lab/orders/${id}/status`, data),
  uploadReport: (id, formData) => api.post(`/partner/lab/orders/${id}/report`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
};

export default labService;
