const crypto = require('crypto');

const ENCRYPTION_SECRET = process.env.ENCRYPTION_SECRET;
const ALGORITHM = 'aes-256-cbc';
const IV_LENGTH = 16; // AES block size

/**
 * Encrypts a plain text string using AES-256-CBC.
 * @param {string} text - The plain text string to encrypt.
 * @returns {string} - The initialization vector and encrypted data, joined by a colon. e.g. "ivHex:encryptedHex"
 */
exports.encrypt = (text) => {
  if (!text) return text;
  if (!ENCRYPTION_SECRET || ENCRYPTION_SECRET.length !== 64) {
    throw new Error('ENCRYPTION_SECRET must be a 64 character hex string (32 bytes)');
  }
  const key = Buffer.from(ENCRYPTION_SECRET, 'hex');
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  
  return iv.toString('hex') + ':' + encrypted;
};

/**
 * Decrypts an encrypted text string previously generated by encrypt().
 * @param {string} encryptedText - The text in "ivHex:encryptedHex" format.
 * @returns {string} - The decrypted plain text.
 */
exports.decrypt = (encryptedText) => {
  if (!encryptedText) return encryptedText;
  if (!ENCRYPTION_SECRET || ENCRYPTION_SECRET.length !== 64) {
    throw new Error('ENCRYPTION_SECRET must be a 64 character hex string (32 bytes)');
  }
  const textParts = encryptedText.split(':');
  if (textParts.length !== 2) return encryptedText; // Fallback if data is not correctly formatted

  const iv = Buffer.from(textParts[0], 'hex');
  const encryptedData = Buffer.from(textParts[1], 'hex');
  const key = Buffer.from(ENCRYPTION_SECRET, 'hex');
  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  
  let decrypted = decipher.update(encryptedData, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  
  return decrypted;
};
